#!/bin/bash

# Import conda script
source ~/anaconda3/etc/profile.d/conda.sh
conda activate ariespipe_py3

# Parse input parameters
targetname=$1
obsdate=$2

# Run each pre-processing for each observing night
echo $targetname / $obsdate

# 1. Cross-talk correction
python ariespipe_crosstalk.py -targetname $targetname -obsdate $obsdate

#2. Dark current correction
python ariespipe_darkcorr.py -targetname $targetname -obsdate $obsdate

# 3.a Find Echelle traces solution
conda activate ariespipe_py27
python ariespipe_findtraces.py -targetname $targetname -obsdate $obsdate
conda activate ariespipe_py3

# 3.b Flat fringes correction
python ariespipe_flatcorr.py -targetname $targetname -obsdate $obsdate

#3.c Flat correction on science frames
python ariespipe_sciencecorr.py -targetname $targetname -obsdate $obsdate

#4. Extract spectra from Echelle traces
conda activate ariespipe_py27
python ariespipe_extractspectra.py -targetname $targetname -obsdate $obsdate
conda activate ariespipe_py3

#5. Bad pixel correction on Spectral Time Series
python ariespipe_badcorr.py -targetname $targetname -obsdate $obsdate

# 6. Alignment of spectra
python ariespipe_alignment_with_stretching.py -targetname $targetname -obsdate $obsdate

# 7. Wavelength calibration
python ariespipe_autowavcal.py -targetname $targetname -obsdate $obsdate
